name: cvm
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - libffi=3.4.2
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - openssl=3.3.2
  - pip=24.2
  - python=3.9.17
  - setuptools=75.1.0
  - tk=8.6.13
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - blinker==1.8.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - eval-type-backport==0.2.0
      - flask==3.0.3
      - flask-wtf==1.2.1
      - fonttools==4.54.1
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - imutils==0.5.4
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightgbm==4.5.0
      - llvmlite==0.43.0
      - mahotas==1.4.18
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - packaging==24.1
      - pandas==1.5.3
      - pillow==10.4.0
      - plotly==5.24.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyod==2.0.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pythresh==0.3.7
      - pytz==2024.2
      - pywavelets==1.6.0
      - pyyaml==6.0.2
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.16.0
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - werkzeug==3.0.4
      - wtforms==3.1.2
      - xgboost==2.1.1
      - zipp==3.20.2
